### ISSUE TITLE
Use pefile instead of winedump

### ISSUE THREAD

**Issue by yan12125** [xantares/mingw-ldd#1]
Just bumped into another interesting project [pefile](https://github.com/erocarrera/pefile), a Python library for analyzing PE/PE+ files. It would be great to drop heavy wine and use a lighter solution.

Tested a random EXE and it looks usable.
```Python
import pefile

pe = pefile.PE('foobar.exe')
for imp in pe.DIRECTORY_ENTRY_IMPORT:
    print(imp.dll)
```
Output:
```
b'ADVAPI32.dll'
b'dbghelp.dll'
b'KERNEL32.dll'
b'SHELL32.dll'
b'WS2_32.dll'
b'msvcrt.dll'
```

**Comment by jschueller** [comment]
yes!

**Comment by xantares** [comment]
Implemented, slightly slower though.
