### ISSUE TITLE
Qt plugins

### ISSUE THREAD

**Issue by mdimura** [xantares/mingw-ldd#2]
I'm trying to use mingw-ldd as a replacement for (not working) windeployqt on linux/mingw. And mingw-ldd correctly lists the main bulk of dependencies, but does not list the qt plugins. Is there a way to workaround this?

**Comment by nurupo** [comment]
Qt plugins are run-time dependencies, not load-time. Those are loaded by Qt at run time with `dlopen()`, `LoadLibrary()` and friends, there is no information about the plugins in the binary's import table. As such, no ldd can detect those, be it this project - mingw-ldd, or the standard Linux ldd utility.

**Comment by mdimura** [comment]
Thank you for your answer! I was hoping, mingw-ldd could somehow parse the `dlopen()` and `LoadLibrary()` calls, I understand now, that it doesn't.
